# 知识库生成脚本 - 生成看板所需的JS数据
import os, re, json
from pathlib import Path

WORKSPACE = r"C:\Users\Administrator\.qclaw\workspace-agent-cf443017"
KNOWLEDGE_DIR = os.path.join(WORKSPACE, "knowledge")

CATEGORIES = {
    "tech": "tech",
    "ai": "ai",
    "lessons": "lessons",
    "ideas": "ideas",
    "workflow": "workflow",
    "system-thinking": "system-thinking",
    "evolution": "evolution",
    "yijing": "yijing",
    "agency-experts": "agency-experts",
}

CATEGORY_LABELS = {
    "tech": "[Tech]",
    "ai": "[AI]",
    "lessons": "[Lessons]",
    "ideas": "[Ideas]",
    "workflow": "[Workflow]",
    "system-thinking": "[System]",
    "evolution": "[Evolution]",
    "yijing": "[Yijing]",
    "agency-experts": "[Experts]",
}

def extract_summary(filepath, max_chars=200):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        if content.startswith('---'):
            end = content.find('---', 3)
            if end != -1:
                content = content[end+3:].strip()
        lines = content.split('\n')
        summary_lines = []
        for line in lines:
            line = line.strip()
            if not line: continue
            if line.startswith('#') or line.startswith('---') or line.startswith('==='): continue
            summary_lines.append(line)
            if len(' '.join(summary_lines)) > max_chars: break
        summary = ' '.join(summary_lines)
        if len(summary) > max_chars: summary = summary[:max_chars] + '...'
        return summary if summary else "no description"
    except Exception as e:
        return "read failed: " + str(e)

def extract_tags(filepath, rel_path):
    tags = []
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        found = re.findall(r'#\w+', content)
        tags.extend([t[1:] for t in found])
        if not tags:
            if rel_path.startswith('tech'): tags = ['tech']
            elif rel_path.startswith('ai'): tags = ['ai']
            elif rel_path.startswith('lessons'): tags = ['lessons']
            elif rel_path.startswith('ideas'): tags = ['idea']
            elif rel_path.startswith('workflow'): tags = ['workflow']
            elif rel_path.startswith('system-thinking'): tags = ['system']
            elif rel_path.startswith('evolution'): tags = ['evolution']
            elif rel_path.startswith('yijing'): tags = ['yijing']
            elif rel_path.startswith('agency-experts'): tags = ['expert']
    except: pass
    return list(set(tags))[:5]

def scan_knowledge():
    entries = []
    for root, dirs, files in os.walk(KNOWLEDGE_DIR):
        for filename in files:
            if not filename.endswith('.md'): continue
            filepath = os.path.join(root, filename)
            rel_path = os.path.relpath(filepath, KNOWLEDGE_DIR)
            cat = "other"
            for key in CATEGORIES:
                if rel_path.startswith(key) or rel_path.startswith(key + os.sep):
                    cat = key; break
            if cat == "other" and "八字" in filename: cat = "lessons"
            date_str = Path(filepath).stem[:10]
            if not (date_str[:4].isdigit()): date_str = ""
            entry = {
                "id": rel_path.replace(os.sep, '/').replace('.md', ''),
                "title": filename.replace('.md', ''),
                "path": filepath.replace('\\', '/'),
                "category": cat,
                "categoryLabel": CATEGORY_LABELS.get(cat, cat),
                "date": date_str,
                "summary": extract_summary(filepath),
                "tags": extract_tags(filepath, rel_path),
                "size": os.path.getsize(filepath),
            }
            entries.append(entry)
    entries.sort(key=lambda x: x['date'], reverse=True)
    return entries

def generate_js_data():
    entries = scan_knowledge()
    cat_counts = {}
    for e in entries:
        cat_counts[e['category']] = cat_counts.get(e['category'], 0) + 1
    
    print("Found %d knowledge entries" % len(entries))
    print("Category stats: " + str(cat_counts))
    
    js_data = """/* =========================================
   KNOWLEDGE_DB -- Knowledge Base Data
   Auto-generated by knowledge_db_generator.py
   Total: %d entries
========================================= */
const KNOWLEDGE_DB = %s;
const KNOWLEDGE_CATS = %s;
const KNOWLEDGE_CATEGORY_META = %s;
""" % (len(entries), json.dumps(entries, ensure_ascii=False, indent=2), json.dumps(cat_counts, ensure_ascii=False), json.dumps(CATEGORY_LABELS, ensure_ascii=False))
    
    output_path = os.path.join(WORKSPACE, "projects", "wuxing-dashboard", "knowledge_db.js")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_data)
    print("Generated: " + output_path)
    
    print("\n[Stats]")
    for cat, count in cat_counts.items():
        print("  %s: %d" % (CATEGORY_LABELS.get(cat, cat), count))
    print("Total: %d" % len(entries))
    return entries, cat_counts

if __name__ == "__main__":
    entries, counts = generate_js_data()