/* =========================================
   KNOWLEDGE_DB -- Knowledge Base Data
   Auto-generated by knowledge_db_generator.py
   Total: 51 entries
========================================= */
const KNOWLEDGE_DB = [
  {
    "id": "ai/2026-04-27-agent-protocol-ecosystem",
    "title": "2026-04-27-agent-protocol-ecosystem",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-27-agent-protocol-ecosystem.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-27",
    "summary": "> 一句话摘要：2026年AI Agent协议已形成四大赛道——智能体与工具(MCP/UTCP)、智能体与智能体(A2A/ANP)、智能体与人(A2UI/AG-UI)、特定领域(UCP/AP2)，MCP+A2A双标准格局初定，Linux基金会AAIF统筹防止生态分裂。 ``` ┌──────────────────────────────────────────────────┐ │       ...",
    "tags": [
      "a2ui",
      "ucp",
      "anp",
      "agent协议",
      "utcp"
    ],
    "size": 10585
  },
  {
    "id": "ai/2026-04-27-开源情报摘要",
    "title": "2026-04-27-开源情报摘要",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-27-开源情报摘要.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-27",
    "summary": "**采集时间**: 19:38:14 (UTC+8) **情报总数**: 45 条 **高价值情报**: 45 条（min_score≥3） **覆盖五行**: 💧水, 🏔️土, 📁其他 | 五行 | 数量 | 代表项目 | |------|------|----------| | 💧 水 | 3 | langchain, open-webui, dify | | 🏔️ 土 | 1 | n8n |...",
    "tags": [
      "ai"
    ],
    "size": 2508
  },
  {
    "id": "tech/2026-04-27-pixelle-video-deep-dive",
    "title": "2026-04-27-pixelle-video-deep-dive",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-27-pixelle-video-deep-dive.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-27",
    "summary": "> 一句话摘要：Pixelle-Video 是阿里AIDC开源的AI短视频全自动引擎，基于ComfyUI模块化架构，支持Windows一键部署，与《AI自动化调研课》高度契合，可直接整合为课程核心案例。 | 维度 | 详情 | |------|------| | **GitHub** | https://github.com/AIDC-AI/Pixelle-Video | | **Stars** ...",
    "tags": [
      "部署评估",
      "架构分析",
      "comfyui",
      "课程整合",
      "开源"
    ],
    "size": 8856
  },
  {
    "id": "ai/2026-04-25-ai-industry-trends-roundup",
    "title": "2026-04-25-ai-industry-trends-roundup",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-25-ai-industry-trends-roundup.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-25",
    "summary": "> 一句话摘要：6条重磅情报——DeepSeek-V4显存暴降90%、阿里开源Pixelle-Video、字节Dramart企业级AI漫剧、ShortVideo Studio 3天造50万爆款、Vibe Coding驯服AI方法论、Hermes自主进化架构对比OpenClaw **核心突破**： - 上下文成本降至1M ctxt的10% - 三件套架构：CSA（压缩稀疏注意力）+ HCA + mH...",
    "tags": [
      "vibe",
      "ai编程",
      "ai工具",
      "国产算力",
      "字节"
    ],
    "size": 6700
  },
  {
    "id": "tech/2026-04-25-crewai-flows-deep-dive",
    "title": "2026-04-25-crewai-flows-deep-dive",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-25-crewai-flows-deep-dive.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-25",
    "summary": "> 研究时间：2026-04-25 > 标签：`#crewai` `#flows` `#multi-agent` `#编排框架` `#事件驱动` CrewAI Flows = **事件驱动的状态机** + **装饰器语法**，让多Agent工作流像搭积木一样清晰可控，比纯Crew模式多了一层精确编排能力。 CrewAI 提供两套互补架构： | 架构 | 关键词 | 适用场景 | |------|-...",
    "tags": [
      "crewai",
      "事件驱动",
      "multi",
      "编排框架",
      "flows"
    ],
    "size": 6584
  },
  {
    "id": "tech/2026-04-24-trendradar-mcp-deep-dive",
    "title": "2026-04-24-trendradar-mcp-deep-dive",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-24-trendradar-mcp-deep-dive.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-24",
    "summary": "> **一句话摘要**: TrendRadar是一个开源AI舆情监控工具，支持多平台热点聚合、RSS订阅、AI智能筛选、MCP架构集成，适合一人公司情报采集。 **日期**: 2026-04-24 **标签**: `#trendradar` `#mcp` `#舆情监控` `#python` `#情报采集` `#五行团队赋能` | 项目 | 详情 | |------|------| | **仓库**...",
    "tags": [
      "python",
      "情报采集",
      "mcp",
      "舆情监控",
      "五行团队赋能"
    ],
    "size": 20141
  },
  {
    "id": "ai/2026-04-23-claude-code-memory-harness-browser",
    "title": "2026-04-23-claude-code-memory-harness-browser",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-23-claude-code-memory-harness-browser.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-23",
    "summary": "> 日期：2026-04-23 > 标签：#记忆系统 #浏览器自动化 #竞品分析 - \"4+1\"结构：四个记录层（公司统一→个人全局→仓库共享→本地私有）+ AutoDream整理系统 - 加载逻辑：1→4顺序加载，4→1优先级执行（越本地优先级越高） - 纯文件系统实现，每条记忆独立.md文件 - **触发条件**：距上次整理≥24小时 + 期间≥5个工作session - **四阶段流程**：...",
    "tags": [
      "竞品分析",
      "浏览器自动化",
      "记忆系统"
    ],
    "size": 2307
  },
  {
    "id": "tech/2026-04-23-fastmcp-deep-dive",
    "title": "2026-04-23-fastmcp-deep-dive",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-23-fastmcp-deep-dive.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-23",
    "summary": "> 2026-04-23 | 技术深度研究 > 来源：GitHub Trending 4/22 简报 P0 优先级 FastMCP 是 PrefectHQ 出品的 Python MCP 框架，以\"声明即工具\"的理念大幅降低 MCP Server 开发门槛，日下载量百万级，已覆盖 70% 的 MCP 服务器。本次研究了其三大支柱架构（Servers/Clients/Apps）、核心源码设计、以及实际...",
    "tags": [
      "python",
      "architecture",
      "prefect",
      "fastmcp",
      "mcp"
    ],
    "size": 7096
  },
  {
    "id": "tech/2026-04-23-langfuse-deep-dive",
    "title": "2026-04-23-langfuse-deep-dive",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-23-langfuse-deep-dive.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-23",
    "summary": "> 2026-04-23 | 技术深度研究 > 来源：GitHub Trending 4/22 简报 P1 优先级 Langfuse 是开源 LLM 工程平台（25k+ stars，YC W23，MIT 协议），提供 Trace 追踪、Prompt 管理、评估引擎、数据集基准测试四大核心能力，是 LLM 应用的\"全生命周期观测系统\"。本次深度分析了其架构设计、存储方案、以及与万能虾 Agent 系...",
    "tags": [
      "prompt",
      "langfuse",
      "llm",
      "observability",
      "clickhouse"
    ],
    "size": 8679
  },
  {
    "id": "workflow/2026-04-22-openclaw-optimization-guide",
    "title": "2026-04-22-openclaw-optimization-guide",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/workflow/2026-04-22-openclaw-optimization-guide.md",
    "category": "workflow",
    "categoryLabel": "[Workflow]",
    "date": "2026-04-22",
    "summary": "> 来源：飞书知识库文章 | 整理：2026-04-22 从省钱和安全两个维度，系统整理了OpenClaw（龙虾）的实战优化方法，包含上下文瘦身、模型混搭、本地模型、安全防护等完整方案。 | 层级 | 原因 | 影响 | |------|------|------| | 全身 | 记忆+工具每次都加载进上下文 | 高 | | 肚子 | 50+内置工具全开 | 中 | | 大腿 | 模型选择不对（烧...",
    "tags": [
      "本地模型",
      "成本优化",
      "OpenClaw",
      "模型混搭",
      "cron"
    ],
    "size": 3838
  },
  {
    "id": "workflow/2026-04-22-openclaw-slimming-guide",
    "title": "2026-04-22-openclaw-slimming-guide",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/workflow/2026-04-22-openclaw-slimming-guide.md",
    "category": "workflow",
    "categoryLabel": "[Workflow]",
    "date": "2026-04-22",
    "summary": "> 来源：用户提供的优化建议 > 日期：2026-04-22 OpenClaw 内置工具分类： | 工具 | 功能 | 频次 | |------|------|------| | read | 读取文件 | 每轮必用 | | write | 写入文件 | 每轮必用 | | edit | 编辑文件 | 高频 | | exec | 执行命令 | 高频 | | cron | 定时任务 | 中频 | | ...",
    "tags": [
      "openclaw",
      "cron",
      "tools",
      "token",
      "heartbeat"
    ],
    "size": 3521
  },
  {
    "id": "ai/2026-04-21-agent-self-evolution-three-breakthroughs",
    "title": "2026-04-21-agent-self-evolution-three-breakthroughs",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-21-agent-self-evolution-three-breakthroughs.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-21",
    "summary": "> 来源：开源情报综合 | 整理：2026-04-21 三大AI技术突破指向同一个方向：AI智能体正在从\"被动工具\"进化为\"主动执行+自我进化\"的数字同事，核心竞争从参数规模转向**思考质量+持续学习能力**。 ``` 监控操作 → 捕获错误 → 立即修复 → 封装技能 ↑                                     ↓ 使用 ←─────────── 技能库 ←───...",
    "tags": [
      "架构",
      "智能体",
      "AI",
      "自进化",
      "持续学习"
    ],
    "size": 3045
  },
  {
    "id": "ai/2026-04-21-ai-interaction-six-elements",
    "title": "2026-04-21-ai-interaction-six-elements",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-21-ai-interaction-six-elements.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-21",
    "summary": "> 来源：AI交互进阶视频 | 整理：2026-04-21 AI回答质量翻倍的关键：不仅要给足背景信息，还要主动邀请AI反问+要求它对不确定内容诚实标注。 1. **角色设定** — 你是谁，你需要AI扮演什么角色 2. **背景信息** — 任务所处的环境/上下文 3. **任务目标** — 你要AI做什么，具体要什么 4. **约束条件** — 限制条件、格式要求、禁止项 **触发机制：** ...",
    "tags": [
      "工作流",
      "AI",
      "Prompt技巧",
      "高效交互"
    ],
    "size": 2127
  },
  {
    "id": "ai/2026-04-21-claude-code-memory-system",
    "title": "2026-04-21-claude-code-memory-system",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-21-claude-code-memory-system.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-21",
    "summary": "> 来源：openclaw-control-ui | 日期：2026-04-21 Claude Code的记忆系统采用\"4+1\"架构（四层配置+AutoDream），核心是**双轨反馈记录**+**三重压缩**+**生物模拟整理**，形成可控、可审、低消耗的记忆闭环。 ``` 层级         位置              共享范围        优先级 ──────────────────...",
    "tags": [
      "AI记忆系统",
      "ClaudeCode",
      "AutoDream",
      "可借鉴",
      "架构设计"
    ],
    "size": 3350
  },
  {
    "id": "ai/2026-04-21-harness-browser-automation",
    "title": "2026-04-21-harness-browser-automation",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-21-harness-browser-automation.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-21",
    "summary": "> 来源：openclaw-control-ui | 日期：2026-04-21 Harness突破传统浏览器自动化框架限制，通过WebSocket直连Chrome DevTools Protocol实现LLM全自由浏览器操作，核心是**自修复机制**+**无框架设计**。 > \"挣脱浏览器框架枷锁，胜任一切浏览器任务\" > —— Gregor Zunic（创始人） **本质**：传统浏览器自动化...",
    "tags": [
      "浏览器自动化",
      "Harness",
      "CDP",
      "自修复",
      "开源工具"
    ],
    "size": 3054
  },
  {
    "id": "ai/2026-04-21-heygen-hyperframes-html-video",
    "title": "2026-04-21-heygen-hyperframes-html-video",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-21-heygen-hyperframes-html-video.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-21",
    "summary": "> 来源：AI视频神器视频 | 整理：2026-04-21 HeyGen Hyperframes通过编写HTML代码生成视频，专为AI智能体设计，适合批量生产成语典故/教学短视频。 - **性质：** 开源AI视频生成工具（GitHub 5.9k stars） - **核心逻辑：** 编写HTML → 生成视频 - **部署方式：** GitHub链接直接部署，本地运行无需复杂配置 - **成本：...",
    "tags": [
      "成语典故",
      "开源",
      "Hyperframes",
      "AI视频",
      "批量生产"
    ],
    "size": 1864
  },
  {
    "id": "ai/2026-04-21-开源情报摘要",
    "title": "2026-04-21-开源情报摘要",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-21-开源情报摘要.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-21",
    "summary": "**采集时间**: 13:00 (UTC+8) **原始情报**: 30 条 **高价值情报**: 30 条 | 五行 | 数量 | |------|------| | 🔥 火 | 0 条 | | 🌳 木 | 0 条 | | 💧 水 | 3 条 | | 🏔️ 土 | 1 条 | | ⚙️ 金 | 0 条 | | 📁 其他 | 26 条 | 1. **[langchain](https://gith...",
    "tags": [
      "ai"
    ],
    "size": 1209
  },
  {
    "id": "ideas/2026-04-21-ai-platform-mastery-methodology",
    "title": "2026-04-21-ai-platform-mastery-methodology",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ideas/2026-04-21-ai-platform-mastery-methodology.md",
    "category": "ideas",
    "categoryLabel": "[Ideas]",
    "date": "2026-04-21",
    "summary": "> **一句话摘要**：从\"普通人玩转OpenClaw\"提炼出的通用方法论——如何系统掌握任何一个AI工具平台。 \"普通人如何玩转OpenClaw\"这个手册本身揭示了一个可迁移的方法论： > **掌握任何AI平台 = 找控制面板 → 拆核心模块 → 注入灵魂 → 扩展技能 → 排错兜底** 这不是OpenClaw专属的，而是适用于Cursor、Dify、Coze、n8n、LangChain等所有A...",
    "tags": [
      "方法论",
      "知识产品",
      "AI平台",
      "元方法论",
      "商业化"
    ],
    "size": 4917
  },
  {
    "id": "ideas/2026-04-21-product-direction-pivot",
    "title": "2026-04-21-product-direction-pivot",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ideas/2026-04-21-product-direction-pivot.md",
    "category": "ideas",
    "categoryLabel": "[Ideas]",
    "date": "2026-04-21",
    "summary": "> 来源：CEO反馈\"拍视频门都没有\"后的认知升级 | 日期：2026-04-21 《AI自动化调研实战课》的产品核心是\"AI自动生成报告\"，不是拍视频。用户不需要出镜，只需要学会\"下指令\"。 ``` 拍视频 → 做内容 → 吸引流量 → 转化变现 问题：CEO不愿意出镜，这条路走不通 ``` ``` 用户给AI地点/需求 → AI自动生成专业.docx调研报告 → 用户交付给客户 卖：工具模板 ...",
    "tags": [
      "产品设计",
      "认知升级",
      "商业模式",
      "调研课"
    ],
    "size": 1595
  },
  {
    "id": "ideas/2026-04-21-yeye-3day-course-ip-acquisition",
    "title": "2026-04-21-yeye-3day-course-ip-acquisition",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ideas/2026-04-21-yeye-3day-course-ip-acquisition.md",
    "category": "ideas",
    "categoryLabel": "[Ideas]",
    "date": "2026-04-21",
    "summary": "> 来源：言也3天课 Day1笔记.pdf > 日期：2026-04-21 > 标签：`#创业` `#IP` `#获客` `#短视频` `#投放` `#信任成交` - **获客**：不是获取点赞/评论等泛互动，而是\"获得会购买的流量\"，购买意愿是核心判定标准。 - **IP本质**：核心目标是\"批量获取会购买的客户\"，需同时满足两大关键——\"精准筛选会购买的人群\"+\"批量吸引该类人群\"。 | 优先...",
    "tags": [
      "获客",
      "IP",
      "投放",
      "创业",
      "短视频"
    ],
    "size": 4923
  },
  {
    "id": "tech/2026-04-21-mcp-server-development",
    "title": "2026-04-21-mcp-server-development",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-21-mcp-server-development.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-21",
    "summary": "> 2026-04-21 | 技术实践 从零开发了一个 MCP Server，学习 MCP 协议、TypeScript 工程化、Web Scraping，并为万能虾增加了实用的学习情报工具。 **工具设计模式**: ```typescript server.registerTool('tool_name', { title: 'Tool Display Name', description: '详...",
    "tags": [
      "openai",
      "mcp",
      "学习项目",
      "工具开发",
      "web"
    ],
    "size": 3427
  },
  {
    "id": "tech/2026-04-21-openai-agents-sdk-deep-dive",
    "title": "2026-04-21-openai-agents-sdk-deep-dive",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-21-openai-agents-sdk-deep-dive.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-21",
    "summary": "> 日期: 2026-04-21 | 标签: #AI #Agent #Python #OpenAI #MCP **OpenAI Agents SDK** 是 OpenAI 官方的多代理工作流框架，继承自 Swarm，是生产级升级版。 | 原语 | 作用 | |------|------| | **Agent** | 装备了指令和工具的 LLM | | **Handoffs** | Agent 之间...",
    "tags": [
      "Python",
      "AI",
      "OpenAI",
      "Agent",
      "MCP"
    ],
    "size": 4538
  },
  {
    "id": "workflow/2026-04-21-openclaw-configuration-methodology",
    "title": "2026-04-21-openclaw-configuration-methodology",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/workflow/2026-04-21-openclaw-configuration-methodology.md",
    "category": "workflow",
    "categoryLabel": "[Workflow]",
    "date": "2026-04-21",
    "summary": "> **一句话摘要**：普通人玩转OpenClaw的系统方法——不是背配置，而是理解\"控制面板→核心模块→灵魂注入→技能扩展→排错兜底\"的递进路径。 **关键认知**：配置文件位置因发行版不同而异 | 发行版 | 配置路径 | |--------|---------| | 原生 OpenClaw | `~/.openclaw/openclaw.json` | | QClaw | `~/.qclaw...",
    "tags": [
      "验证修正",
      "配置",
      "openclaw",
      "入门指南",
      "方法论"
    ],
    "size": 5553
  },
  {
    "id": "workflow/2026-04-21-task-reception-checklist",
    "title": "2026-04-21-task-reception-checklist",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/workflow/2026-04-21-task-reception-checklist.md",
    "category": "workflow",
    "categoryLabel": "[Workflow]",
    "date": "2026-04-21",
    "summary": "> 转化自：AI交互六要素 | 创建：2026-04-21 | 位置：workspace根目录 每次接任务，先自检六要素：角色、背景、目标、约束、邀请补充、诚实标注。信息完整再执行。 | 序号 | 要素 | 检查问题 | 缺失处理 | |------|------|----------|----------| | 1 | 角色 | 我需要扮演什么角色？ | 默认：万能虾CEO | | 2 | 背景...",
    "tags": [
      "自检清单",
      "工作流",
      "质量提升",
      "六要素"
    ],
    "size": 1998
  },
  {
    "id": "ai/2026-04-20-开源情报摘要",
    "title": "2026-04-20-开源情报摘要",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-20-开源情报摘要.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-20",
    "summary": "﻿# 📡 开源情报摘要 — 2026-04-20 **采集时间**: 13:04:35 (UTC+8) | 指标 | 数量 | |------|------| | 原始情报 | 45 条 | | 高价值情报 | 45 条 | - 🔥 火: 0 条 - 🌳 木: 0 条 - 💧 水: 3 条 (langchain, open-webui, dify) - 🏔️ 土: 1 条 (n8n) - ⚙️ 金...",
    "tags": [
      "ai"
    ],
    "size": 651
  },
  {
    "id": "tech/2026-04-20-edge-tts-protocol-experiment",
    "title": "2026-04-20-edge-tts-protocol-experiment",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-20-edge-tts-protocol-experiment.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-20",
    "summary": "手动实现微软 Bing Speech TTS 的 WebSocket 协议，脱离官方 SDK 依赖。 ```javascript const WSS_URL = 'wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1' const requestId = generateUUID() const ws...",
    "tags": [
      "WebSocket",
      "EdgeTTS",
      "协议分析",
      "语音合成"
    ],
    "size": 3488
  },
  {
    "id": "tech/2026-04-20-HTML-CSS基础学习",
    "title": "2026-04-20-HTML-CSS基础学习",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-20-HTML-CSS基础学习.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-20",
    "summary": "**日期**：2026-04-20 **阶段**：前端开发 Day 1 **目标**：掌握HTML/CSS基础，能制作简单静态页面 ```html <!DOCTYPE html>          <!-- 声明文档类型 --> <html lang=\"zh-CN\">      <!-- 根元素，lang指定语言 --> <head>                   <!-- 头部：元数据 -...",
    "tags": [
      "667eea",
      "764ba2",
      "333",
      "header"
    ],
    "size": 6649
  },
  {
    "id": "tech/2026-04-20-langchain架构分析",
    "title": "2026-04-20-langchain架构分析",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-20-langchain架构分析.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-20",
    "summary": "- **项目**: langchain - **Stars**: 134,098 - **语言**: Python - **定位**: Agent工程平台 - **关键词**: RAG, LangChain, agents, AI 1. **Chain模块** - 链式调用编排 - 支持多种LLM后端 - 可组合的组件设计 2. **Agent模块** - 工具调用机制 - 记忆管理 - 决策逻辑...",
    "tags": [
      "Agent工程",
      "RAG",
      "AI架构",
      "Python",
      "langchain"
    ],
    "size": 3628
  },
  {
    "id": "tech/2026-04-20-short-video-factory-architecture",
    "title": "2026-04-20-short-video-factory-architecture",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-20-short-video-factory-architecture.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-20",
    "summary": "自动化短视频生成工具，支持 AI 文案生成 → TTS 语音合成 → 视频片段处理 → FFmpeg 合成完整视频。 | 层级 | 技术选型 | |------|----------| | 前端 | Vue 3 + TypeScript + Vite | | 桌面 | Electron | | TTS | Edge TTS (微软 Bing Speech WebSocket) | | 视频处理 |...",
    "tags": [
      "FFmpeg",
      "EdgeTTS",
      "自动化",
      "Electron",
      "Vue3"
    ],
    "size": 4077
  },
  {
    "id": "workflow/2026-04-20-自主学习框架",
    "title": "2026-04-20-自主学习框架",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/workflow/2026-04-20-自主学习框架.md",
    "category": "workflow",
    "categoryLabel": "[Workflow]",
    "date": "2026-04-20",
    "summary": "**主动学习 > 被动响应** - 每天自动学习新知识 - 定期更新技能库 - 主动发现学习机会 - 建立知识反馈循环 - 每日行业趋势分析 - 竞争对手动态追踪 - 技术路线图预测 - 每周战略报告 - 新工具/框架学习 - 用户增长方法论 - 内容创作技巧 - 营销策略研究 - 每日开源项目分析 - 新技术实验 - 架构设计模式 - 性能优化技巧 - 自动化流程优化 - 工具链整合 - 效率方...",
    "tags": [
      "workflow"
    ],
    "size": 2767
  },
  {
    "id": "ai/2026-04-19-fish-audio-s2-voice-clone-guide",
    "title": "2026-04-19-fish-audio-s2-voice-clone-guide",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-19-fish-audio-s2-voice-clone-guide.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-19",
    "summary": "> 五行执行·火·立即可用 | 更新：2026-04-19 | 项目 | 状态 | |------|------| | 模型文件 | 🔄 下载中（ModelScope，速度~200KB/s）| | 模型路径 | `models/fishaudio/s2-pro/` | | 预计完成 | ~14小时（10GB模型）| | Python环境 | Python 3.14 + ModelScope 1.3...",
    "tags": [
      "ai"
    ],
    "size": 5399
  },
  {
    "id": "ai/2026-04-19-short-video-factory-guide",
    "title": "2026-04-19-short-video-factory-guide",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-19-short-video-factory-guide.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-19",
    "summary": "> 五行执行·火·立即可用 | 更新：2026-04-19 | 项目 | 状态 | |------|------| | 源码 | ✅ 已下载至 `short-video-factory/` | | 安装 | ⏳ 待安装依赖 | | Node.js | 待检测 | | pnpm | 待检测 | **短视频工厂**（Short Video Factory）是一个 AI 驱动的桌面端应用： - **技术...",
    "tags": [
      "ai"
    ],
    "size": 5218
  },
  {
    "id": "ai/2026-04-19-数字分身商业模型-JNagent分析",
    "title": "2026-04-19-数字分身商业模型-JNagent分析",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-19-数字分身商业模型-JNagent分析.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-19",
    "summary": "深圳\"嘉年智合\"（JN agent）将设计师20年经验数字化为AI工作流，验证了\"私有content飞轮\"商业模式的可行性，为个人/小团队提供了AI时代轻量化创业的标杆案例。 **\"私有 content 飞轮\" = 经验拆解 → 数据资产 → AI工作流 → 商业交付** - 夏江南20年设计经验 → 拆解为可训练数据集 - AI工作流参与实际项目交付 - 形成自我强化的飞轮效应 | 能力 | 描...",
    "tags": [
      "ai"
    ],
    "size": 2050
  },
  {
    "id": "workflow/2026-04-19-Qclaw备份系统精华分析",
    "title": "2026-04-19-Qclaw备份系统精华分析",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/workflow/2026-04-19-Qclaw备份系统精华分析.md",
    "category": "workflow",
    "categoryLabel": "[Workflow]",
    "date": "2026-04-19",
    "summary": "- **基础镜像**：一次性完整备份（285.81MB，3888个文件） - **每日增量**：只备份当天修改的文件 - **时间轴恢复**：基础镜像 + 截至指定日期的所有增量 = 该日状态 ``` 排除内容： - 可重建内容：node_modules、compile-cache、browser/canvas缓存 - 旧备份：skills_backup_*、backups - 临时文件：ocr_...",
    "tags": [
      "workflow"
    ],
    "size": 5265
  },
  {
    "id": "ai/2026-04-18-github-trending-absorption",
    "title": "2026-04-18-github-trending-absorption",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ai/2026-04-18-github-trending-absorption.md",
    "category": "ai",
    "categoryLabel": "[AI]",
    "date": "2026-04-18",
    "summary": "**日期：2026年4月18日** **标签：AI-Agent, 自进化, GitHub-Trending, 五行团队** 1. **obra/superpowers** - 智能技能框架 - **吸收点**：方法论框架，如何构建可扩展的技能系统 - **应用**：五行团队的工作流设计 2. **lsdefine/GenericAgent** - 自进化Agent - **吸收点**：从3.3K行...",
    "tags": [
      "ai"
    ],
    "size": 3887
  },
  {
    "id": "ideas/2026-04-17-易经大脑与AI技术融合思路",
    "title": "2026-04-17-易经大脑与AI技术融合思路",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/ideas/2026-04-17-易经大脑与AI技术融合思路.md",
    "category": "ideas",
    "categoryLabel": "[Ideas]",
    "date": "2026-04-17",
    "summary": "基于GitHub Trending技术趋势，探索易经思维与AI代码生成、量子计算、系统设计等技术的融合可能性。 **问题**：当前AI代码生成工具缺乏\"哲学指导\" **思路**：将易经的\"变易、简易、不易\"原则融入代码生成逻辑 - **变易原则**：代码应随需求变化而灵活调整 - AI生成代码时考虑扩展性和可维护性 - 自动识别代码中的\"刚性\"部分，建议柔性设计 - **简易原则**：复杂问题简单...",
    "tags": [
      "创新思路",
      "AI融合",
      "技术哲学",
      "系统架构",
      "量子计算"
    ],
    "size": 3604
  },
  {
    "id": "tech/2026-04-17-github-trending-tech-analysis",
    "title": "2026-04-17-github-trending-tech-analysis",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-17-github-trending-tech-analysis.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-17",
    "summary": "分析今日GitHub Trending热门项目，识别AI代码生成、量子计算、隐私合规、边缘AI等四大技术趋势。 - **项目**：DeepCoder-X (⭐5,432，新增1,234) - **特点**：支持多语言实时转换和智能调试 - **趋势**：AI编程工具从代码补全向\"语言翻译+智能调试\"演进 - **技术栈**：Python - **项目**：QuantumOS/qkernel (⭐4...",
    "tags": [
      "技术分析",
      "技术趋势",
      "隐私合规",
      "AI代码生成",
      "GitHubTrending"
    ],
    "size": 2423
  },
  {
    "id": "evolution/2026-04-16-evolution-methodology",
    "title": "2026-04-16-evolution-methodology",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/evolution/2026-04-16-evolution-methodology.md",
    "category": "evolution",
    "categoryLabel": "[Evolution]",
    "date": "2026-04-16",
    "summary": "进化不是随机变化，而是**有方向的适应性改进**。通过设计好的进化机制，可以加速能力提升。 - **多样性产生**：创造不同的解决方案 - **随机探索**：尝试新的可能性 - **组合创新**：将现有元素重新组合 - **适应性评估**：评估解决方案的效果 - **优胜劣汰**：保留有效的，淘汰无效的 - **目标导向**：根据目标进行选择 - **经验传承**：将有效经验传递给下一代 - **...",
    "tags": [
      "evolution"
    ],
    "size": 7243
  },
  {
    "id": "system-thinking/2026-04-16-system-thinking-framework",
    "title": "2026-04-16-system-thinking-framework",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/system-thinking/2026-04-16-system-thinking-framework.md",
    "category": "system-thinking",
    "categoryLabel": "[System]",
    "date": "2026-04-16",
    "summary": "系统思考不是分析各个部分，而是理解各部分之间的**相互关系**和**整体行为**。 - **涌现性**：系统整体表现出各部分没有的特性 - **非线性**：小变化可能引发大影响 - **反馈循环**：各部分的相互作用 - **连接性**：元素如何相互连接 - **依赖性**：一个元素如何影响另一个 - **网络效应**：连接形成的整体效应 - **时间维度**：系统如何随时间变化 - **演化路径...",
    "tags": [
      "system"
    ],
    "size": 5543
  },
  {
    "id": "yijing/2026-04-16-yijing-thinking-workflow",
    "title": "2026-04-16-yijing-thinking-workflow",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/yijing/2026-04-16-yijing-thinking-workflow.md",
    "category": "yijing",
    "categoryLabel": "[Yijing]",
    "date": "2026-04-16",
    "summary": "- **阴阳平衡**：任何决策都考虑正反两面 - **五行相生**：知识→技能→经验→智慧→创新的循环 - **八卦系统**：八个维度全面思考问题 - **太极生两仪**：问题分解为阴阳两个角度 - **四象定位**：用四个象限快速定位问题性质 - **八卦归类**：将复杂问题归入八个基本类型 - **六十四卦**：64种情境应对策略 - **爻变思维**：关注微小变化带来的连锁反应 - **时位...",
    "tags": [
      "yijing"
    ],
    "size": 5183
  },
  {
    "id": "lessons/2026-04-13-八字排盘系统错误诊断修复",
    "title": "2026-04-13-八字排盘系统错误诊断修复",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/lessons/2026-04-13-八字排盘系统错误诊断修复.md",
    "category": "lessons",
    "categoryLabel": "[Lessons]",
    "date": "2026-04-13",
    "summary": "> 记录时间：2026-04-13 用户两次反馈： 1. **万年历换算出错** — 农历1985年2月21日戌时，多次换算结果错误，偏差近一个月 2. **四柱一直弄错** — 排盘结果和实际八字不符 写诊断脚本 `diag2.py`，系统验证： - 农历→公历：`lunardate` 库给出 1985年2月21日 → 1985-04-10 ✅ 正确 - 日柱手算 vs cnlunar：`lun...",
    "tags": [
      "lessons"
    ],
    "size": 3698
  },
  {
    "id": "lessons/2026-04-13-八字数理五行易错点",
    "title": "2026-04-13-八字数理五行易错点",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/lessons/2026-04-13-八字数理五行易错点.md",
    "category": "lessons",
    "categoryLabel": "[Lessons]",
    "date": "2026-04-13",
    "summary": "> 记录时间：2026-04-13 **错误**：把5画归为木，把6画归为火。 **正确法则（必须按这个记）**： - 1、2 画 → 木（单数甲木，双数乙木） - 3、4 画 → 火（单数丙火，双数丁火） - 5、6 画 → 土（单数戊土，双数己土） - 7、8 画 → 金（单数庚金，双数辛金） - 9、0 画 → 水（单数壬水，双数癸水） **口诀**：木1-2，火3-4，土5-6，金7-8，...",
    "tags": [
      "lessons"
    ],
    "size": 1874
  },
  {
    "id": "tech/2026-04-13-姓名五行判断完整流程",
    "title": "2026-04-13-姓名五行判断完整流程",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-13-姓名五行判断完整流程.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-13",
    "summary": "> 记录时间：2026-04-13 > 来源：用户纠正+整理 > ⚠️ **判断五行之前，必须先确认前提：这个字是什么身份？** > 不同身份 → 不同判断方法，搞错前提就全错。 | 前提 | 说明 | |------|------| | 是**姓氏**吗？ | → 100% 数理五行，不管有没有五行偏旁部首 | | 是**名字**吗？ | → 优先偏旁部首五行，找不到再转数理五行 | | 没给姓...",
    "tags": [
      "tech"
    ],
    "size": 5816
  },
  {
    "id": "tech/2026-04-12-context-memory-rag",
    "title": "2026-04-12-context-memory-rag",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/tech/2026-04-12-context-memory-rag.md",
    "category": "tech",
    "categoryLabel": "[Tech]",
    "date": "2026-04-12",
    "summary": "> **一句话摘要**：超长上下文是暴力解法，知识库+记忆是聪明解法。 | 概念 | 本质 | 优势 | 劣势 | |------|------|------|------| | **超长上下文** | 模型一次能看多少 token | 不需要额外基础设施 | 太长会稀释注意力，大海捞针效果差 | | **长期记忆** | 跨会话的持久化存储 | 不依赖模型升级，软件层可控 | 需要主动维护，检索...",
    "tags": [
      "架构",
      "RAG",
      "AI",
      "上下文管理",
      "记忆系统"
    ],
    "size": 1413
  },
  {
    "id": "INDEX",
    "title": "INDEX",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/INDEX.md",
    "category": "other",
    "categoryLabel": "other",
    "date": "",
    "summary": "> 万能虾的知识库索引 ``` knowledge/ ├── tech/        # 技术学习 ├── ai/          # AI 相关 ├── lessons/     # 踩坑经验 ├── ideas/       # 灵感创意 ├── workflow/    # 工作流程 ├── system-thinking/  # 系统思维 ├── evolution/   # 进化方法...",
    "tags": [
      "vibe",
      "openai",
      "a2ui",
      "fastmcp",
      "cron"
    ],
    "size": 4749
  },
  {
    "id": "_cross_ref",
    "title": "_cross_ref",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/_cross_ref.md",
    "category": "other",
    "categoryLabel": "other",
    "date": "",
    "summary": "> 万能虾内部知识连接索引 | 维护：每次心跳时更新 > 创建：2026-04-21 | 上次更新：2026-04-21 > 知识不是孤岛，关联才是力量。每条新知识，必须找到它的邻居。 ``` AI交互六要素 │ ├── ↔ OpenClaw配置方法论 │       └── 关联点：两者都是\"方法论\"类知识 │           用途：用六要素优化OpenClaw配置任务的prompt │ ├...",
    "tags": [],
    "size": 7578
  },
  {
    "id": "八字取名知识库",
    "title": "八字取名知识库",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/八字取名知识库.md",
    "category": "lessons",
    "categoryLabel": "[Lessons]",
    "date": "",
    "summary": "> 来源：男女忌用字+12生肖宜忌字+五行取名法则.xls > 整理时间：2026-04-13 > 适用场景：八字起名、姓名学分析 | 分类 | 生肖 | |------|------| | **大属相**（可用出头字、大、天、王等） | 鼠、虎、龙、蛇、马、猴 | | **小属相**（禁用出头字，宜低调内敛） | 牛、兔、鸡、羊、狗、猪 | > 核心原则：小属相不宜用\"大\"\"天\"\"王\"\"中\"\"出...",
    "tags": [],
    "size": 18760
  },
  {
    "id": "agency-experts/growth-framework",
    "title": "growth-framework",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/agency-experts/growth-framework.md",
    "category": "agency-experts",
    "categoryLabel": "[Experts]",
    "date": "",
    "summary": "> 来源：growth-hacker + trend-researcher > 整理：万能虾 | 2026-04-23 ``` 渠道分析矩阵 | 渠道 | 流量 | CAC | 质量 | 优先级 | |------|------|-----|------|--------| | 自然搜索 | 高 | ¥0 | ⭐⭐⭐⭐⭐ | P0 | | 付费广告 | 高 | ¥50 | ⭐⭐⭐⭐ | P1 | ...",
    "tags": [
      "EXP"
    ],
    "size": 2829
  },
  {
    "id": "agency-experts/INDEX",
    "title": "INDEX",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/agency-experts/INDEX.md",
    "category": "agency-experts",
    "categoryLabel": "[Experts]",
    "date": "",
    "summary": "> 创建时间：2026-04-23 > 来源：61个agency-agents专家技能包精选 ``` knowledge/agency-experts/ ├── INDEX.md                    # 本索引 ├── growth-framework.md         # 增长黑客核心框架 ├── api-design-patterns.md      # API设计最佳实...",
    "tags": [
      "expert"
    ],
    "size": 1727
  },
  {
    "id": "agency-experts/quality-gate",
    "title": "quality-gate",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/agency-experts/quality-gate.md",
    "category": "agency-experts",
    "categoryLabel": "[Experts]",
    "date": "",
    "summary": "> 来源：reality-checker > 整理：万能虾 | 2026-04-23 **证据第一** — 不接受未经验证的声明 **严格但公平** — 坚持标准，考虑业务上下文 **默认怀疑** — 除非压倒性证据，否则需要更多工作 - [ ] 所有计划功能已实现 - [ ] 验收标准全部满足 - [ ] 用户故事已完成 - [ ] 边缘情况已处理 - [ ] 错误处理完善 - [ ] 功能测试...",
    "tags": [
      "expert"
    ],
    "size": 2083
  },
  {
    "id": "workflow/技能库-基线评估",
    "title": "技能库-基线评估",
    "path": "C:/Users/Administrator/.qclaw/workspace-agent-cf443017/knowledge/workflow/技能库-基线评估.md",
    "category": "workflow",
    "categoryLabel": "[Workflow]",
    "date": "",
    "summary": "**熟练度等级：** - ⭐ 入门：了解概念，能简单使用 - ⭐⭐ 熟练：能独立完成任务 - ⭐⭐⭐ 精通：能解决复杂问题，指导他人 - ⭐⭐⭐⭐ 专家：能创新、优化、设计系统 - GitHub趋势分析 ⭐⭐ - 技术路线预测 ⭐ - 竞争对手追踪 ⭐ - 产品定位分析 ⭐⭐ - 市场机会识别 ⭐ - 资源分配规划 ⭐ - 新框架快速上手 ⭐⭐⭐ - 文档阅读能力 ⭐⭐⭐ - 示例代码分析 ⭐⭐⭐...",
    "tags": [
      "workflow"
    ],
    "size": 2537
  }
];
const KNOWLEDGE_CATS = {"ai": 15, "tech": 14, "workflow": 7, "ideas": 4, "evolution": 1, "system-thinking": 1, "yijing": 1, "lessons": 3, "other": 2, "agency-experts": 3};
const KNOWLEDGE_CATEGORY_META = {"tech": "[Tech]", "ai": "[AI]", "lessons": "[Lessons]", "ideas": "[Ideas]", "workflow": "[Workflow]", "system-thinking": "[System]", "evolution": "[Evolution]", "yijing": "[Yijing]", "agency-experts": "[Experts]"};
